<div class="sect1">
<h2 id="_description">Description</h2>
<div class="sectionbody">

</div>
</div>
<div class="sect1">
<h2 id="_why_is_this_an_issue">Why is this an issue?</h2>
<div class="sectionbody">
<div class="paragraph">
<p>The purpose of a <code>finally</code> block is to ensure the cleanup of objects (e.g. closing the file), it is executed after <code>try</code> and <code>catch</code> blocks under any circumstances. Having a <code>return</code> or a thrown exception in a <code>finally</code> block suppresses the propagation of any unhandled exception which was thrown in the <code>try</code> or <code>catch</code> block or overwrite the returned value.</p>
</div>
<div class="paragraph">
<p>This rule will report on all usages of jump statements (<code>return</code>, <code>break</code>, <code>throw</code>, and <code>continue</code>) from a <code>finally</code> block. Even if it&#8217;s guaranteed that no unhandled exception can happen in <code>try</code> or <code>catch</code> blocks, it&#8217;s not recommended to use any jump statements inside the <code>finally</code> to have the logic there limited to the "cleanup".</p>
</div>
<div class="sect2">
<h3 id="_noncompliant_code_example">Noncompliant code example</h3>
<div class="listingblock">
<div class="content">
<pre class="highlight"><code class="language-javascript" data-lang="javascript">async function foo() {
    let result, connection;
    try {
        connection = await connect();
        result = connection.send(1);
    } catch(err) {
        console.error(err.message); // if this line throws, this exception will not be propagated
    } finally {
        connection.close();
        return result;              // Noncompliant
    }
}</code></pre>
</div>
</div>
</div>
<div class="sect2">
<h3 id="_compliant_solution">Compliant solution</h3>
<div class="listingblock">
<div class="content">
<pre class="highlight"><code class="language-javascript" data-lang="javascript">async function foo() {
    let result, connection;
    try {
        connection = await connect();
        result = connection.send(1);
    } catch(err) {
        console.error(err.message);
    } finally {
        connection.close();
    }
    return result;
}</code></pre>
</div>
</div>
</div>
</div>
</div>
<div class="sect1">
<h2 id="_resources">Resources</h2>
<div class="sectionbody">
<div class="ulist">
<ul>
<li>
<p><a href="https://cwe.mitre.org/data/definitions/584">MITRE, CWE-584</a> - Return Inside Finally Block</p>
</li>
</ul>
</div>
<hr>
</div>
</div>
<div class="sect1">
<h2 id="_implementation_specification">Implementation Specification</h2>
<div class="sectionbody">
<div class="paragraph">
<p>(visible only on this page)</p>
</div>
<div class="sect2">
<h3 id="_message">Message</h3>
<div class="paragraph">
<p>Remove this "xxx" statement from this "finally" block.</p>
</div>
<hr>
</div>
</div>
</div>
<div class="sect1">
<h2 id="_comments_and_links">Comments And Links</h2>
<div class="sectionbody">
<div class="paragraph">
<p>(visible only on this page)</p>
</div>
<div class="sect2">
<h3 id="_on_25_jul_2013_164513_freddy_mallet_wrote">on 25 Jul 2013, 16:45:13 Freddy Mallet wrote:</h3>
<div class="paragraph">
<p>Is implemented by SONARJAVA-231</p>
</div>
</div>
<div class="sect2">
<h3 id="_on_27_feb_2015_101100_freddy_mallet_wrote">on 27 Feb 2015, 10:11:00 Freddy Mallet wrote:</h3>
<div class="paragraph">
<p>FYI @Ann, in the Klockwork java analyser, this rule is associated to OWASP Top 10 A5 category: http://docs.klocwork.com/Insight-10.0/Checkers:JD.FINRET</p>
</div>
</div>
<div class="sect2">
<h3 id="_on_27_feb_2015_134237_ann_campbell_wrote">on 27 Feb 2015, 13:42:37 Ann Campbell wrote:</h3>
<div class="paragraph">
<p>\[~freddy.mallet] I find the association tenuous at best.</p>
</div>
</div>
</div>
</div>